language: ruby
# cache: bundler
rvm:
  - 2.2.1
env:
  - DB=<sqlite></sqlite>
  # - DB=redis
scripts:
  - "bundle exec rspec spec/"
before_script:
  - RAILS_ENV=test bundle exec rake --trace db:drop db:create db:migrate test
before_install:
  - sudo apt-get install redis-server
branches:
  only:
    - master
    - ci
addons:
  code_climate:
    repo_token: 449a328be55428037a4a807eeb5e3f42af0a88fb0b4c7f15a2a6e13552124479

