vol:
  image: postgres
  volumes:
    - ./data:/var/lib/postgresql/data

redis:
  image: redis
  ports:
    - "6379:6379"

db:
  image: postgres:latest
  ports:
    - "5432:5432"
  volumes_from:
    - vol
nginx:
  build: ./script/nginx
  ports:
    - "80:80"
  volumes:
    - /var/log/nginx/:/var/log/nginx
  links:
    - web
  volumes_from:
    - web
# haproxy:
#   build: ./script/haproxy
#   ports:
#     - "8080:80"
#   links:
#     - nginx
web:
  build: .
  ports:
    - "3000:3000"
  environment:
    - DEBUG=false
    - SEND_EMAILS=false
    # - POSTGRES_PASSWORD=docker
    - POSTGRES_HOST=db
    - POSTGRES_USER=postgres
    - RAILS_ENV=development
    - REDIS_URI=redis
  # command: service unicorn-server start
  command: ./script/rails/docker-entrypoint.sh
  # command: bundle exec rails s -p 3000 -b '0.0.0.0'
  # command: bundle exec unicorn -E development -c config/unicorn/devlopment.rb -d
  volumes:
    - .:/app
  links:
    - redis
    - db
elasticsearch:
  build: ./script/elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./script/logstash/config:/etc/logstash/conf.d
    - ./log:/tmp/rapi
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  build: ./script/kibana/
  volumes:
    - ./script/kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
