
development:
  name: api
  redis_connection:  redis://redis/0 #ENV['REDIS_URI']
  thread_safe: true

test:
  name: api
  redis_connection: redis://redis/0 #ENV['REDIS_URI'] #redis://@localhost:6379/0
  thread_safe: true


production:
  name: api
  redis_connection: redis://redis/0 #ENV['REDIS_URI'] #redis://username:password@localhost:6379/0
  thread_safe: true
